datablock WeaponData(BaseThrowing)
{
    .local = 1;
    .hitDirection[0] = "";
    .hitDirection[1] = "";
    .hitDirection[2] = "";
    .hitDirection[3] = "";
    .correctMuzzleVector = 0;
    .stateName[0] = "Ready";
    .stateTransitionOnTriggerDown[0] = "PreFire";
    .stateScript[0] = "onRangedImageReady";
    .stateName[1] = "PreFire";
    .stateFireSubState[1] = PreFire;
    .stateTransitionOnTimeout[1] = "PreFire_onTimeout";
    .stateTransitionOnTriggerUp[1] = "Fire";
    .stateTransitionOnAltTriggerDown[1] = "FireCancel";
    .stateWaitForTimeout[1] = 0;
    .stateAllowImageChange[1] = 0;
    .stateSequence[1] = "Throw_prefire";
    .stateDirection[1] = 1;
    .stateFreezeAnimation[1] = 0;
    .stateName[2] = "PreFire_onTimeout";
    .stateFireSubState[2] = PreFire;
    .stateTransitionOnTriggerUp[2] = "Fire";
    .stateTransitionOnAltTriggerDown[2] = "FireCancel";
    .stateAllowImageChange[2] = 0;
    .stateSequence[2] = "Throw_prefire";
    .stateName[3] = "PreFire_onTrigerUp";
    .stateFireSubState[3] = PreFire;
    .stateTransitionOnTimeout[3] = "Fire";
    .stateTransitionOnAltTriggerDown[3] = "FireCancel";
    .stateWaitForTimeout[3] = 0;
    .stateAllowImageChange[3] = 0;
    .stateName[4] = "FireCancel";
    .stateTransitionOnTimeout[4] = "FireCancelRecoil";
    .stateAllowImageChange[4] = 0;
    .stateName[5] = "Fire";
    .stateFireSubState[5] = Fire;
    .stateFire[5] = 1;
    .stateTransitionOnTimeout[5] = "PostFireWait";
    .stateTransitionOnAltTriggerDown[5] = "FireCancelRecoil";
    .stateWaitForTimeout[5] = 0;
    .stateAllowImageChange[5] = 0;
    .stateScript[5] = "onThrowingWeaponFire";
    .stateName[6] = "FireCancelRecoil";
    .stateTransitionOnTimeout[6] = "PostFireWaitForTriggerUp";
    .stateAllowImageChange[6] = 0;
    .stateName[7] = "PostFireWait";
    .stateFireSubState[7] = PostFire;
    .stateTimeoutValue[7] = 0.5;
    .stateTransitionOnTimeout[7] = "PostFireDrawWeapon";
    .stateAllowImageChange[7] = 0;
    .stateName[8] = "PostFireDrawWeapon";
    .stateTransitionOnTimeout[8] = "Draw";
    .stateAllowImageChange[8] = 0;
    .stateScript[8] = "onThrowingWeaponPostfire";
    .stateName[9] = "PostFireWaitForTriggerUp";
    .stateTransitionOnTriggerUp[9] = "PostFireWaitForAltTriggerUp";
    .stateAllowImageChange[9] = 0;
    .stateName[10] = "PostFireWaitForAltTriggerUp";
    .stateTransitionOnAltTriggerUp[10] = "Ready";
    .stateAllowImageChange[10] = 0;
    .stateName[11] = "Draw";
    .stateFireSubState[11] = Draw;
    .stateTransitionOnTimeout[11] = "Ready";
    .stateWaitForTimeout[11] = 1;
    .stateAllowImageChange[11] = 0;
    .stateName[12] = "Attach";
    .stateFireSubState[12] = Attached;
    .stateAllowImageChange[12] = 1;
};
datablock ArrowData(ThrowingKnifeProjectile)
{
    .id = 577;
    .sound = "ThrowingFlySound";
    .stuckArrowLifeTime = 1000;
    .projectileShape = "art/models/3d-2d/weapons/ammunition/throwingknife_export_01.dts";
    .upForce = 0;
    .Friction = 0.15;
    .shapeFile = "art/models/3d-2d/weapons/ammunition/throwingknife_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .correctMuzzleVector = 0;
    .weaponType = WeaponAmmo;
};
datablock ThrowingWeaponData(ThrowingKnife : BaseThrowing)
{
    .id = 578;
    .Object_typeID = 608;
    .shapeFile = "art/models/3d-2d/weapons/ammunition/throwingknife_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .hitGroupType[0] = Slashing;
    .hitGroupDmgLevel[0] = 3.2;
    .WoundMultiplier = 0.1;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .AgilityNeed = 20;
    .StrengthNeed = 10;
    .MaxAccuracy = 1.3;
    .Emax = 12;
    .BasePrefireAnimTime = 0.5;
    .BaseRecoilAnimTime = 0.2;
    .StaminaRate = 30;
    .attackType = AttackThrowing;
    .weaponType = WeaponThrowing;
    .projectileData = "ThrowingKnifeProjectile";
};
datablock ArrowData(ThrowingJavelinProjectile)
{
    .id = 579;
    .sound = "ThrowingFlySound";
    .stuckArrowLifeTime = 1000;
    .projectileShape = "art/models/3d-2d/weapons/ammunition/throwingspear_export_01.dts";
    .upForce = 0;
    .Friction = 0.08;
    .shapeFile = "art/models/3d-2d/weapons/ammunition/throwingspear_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .correctMuzzleVector = 0;
    .weaponType = WeaponAmmo;
};
datablock ThrowingWeaponData(ThrowingJavelin : BaseThrowing)
{
    .id = 580;
    .Object_typeID = 609;
    .shapeFile = "art/models/3d-2d/weapons/ammunition/throwingspear_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 2.15;
    .WoundMultiplier = 0.09;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .AgilityNeed = 20;
    .StrengthNeed = 30;
    .MaxAccuracy = 1.2;
    .Emax = 28;
    .BasePrefireAnimTime = 0.5;
    .BaseRecoilAnimTime = 0.2;
    .StaminaRate = 50;
    .attackType = AttackThrowing;
    .weaponType = WeaponThrowing;
    .projectileData = "ThrowingJavelinProjectile";
};
datablock ArrowData(ThrowingAxeProjectile)
{
    .id = 573;
    .sound = "ThrowingFlySound";
    .stuckArrowLifeTime = 1000;
    .projectileShape = "art/models/3d-2d/weapons/ammunition/francisca_export_01.dts";
    .upForce = 0;
    .Friction = 0.25;
    .shapeFile = "art/models/3d-2d/weapons/ammunition/francisca_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .correctMuzzleVector = 0;
    .weaponType = WeaponAmmo;
};
datablock ThrowingWeaponData(ThrowingAxe : BaseThrowing)
{
    .id = 574;
    .Object_typeID = 610;
    .shapeFile = "art/models/3d-2d/weapons/ammunition/francisca_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .hitGroupType[0] = Chopping;
    .hitGroupDmgLevel[0] = 2.75;
    .WoundMultiplier = 0.06;
    .FractureMultiplier = 0.095;
    .StunMultiplier = 0;
    .AgilityNeed = 30;
    .StrengthNeed = 30;
    .MaxAccuracy = 1.2;
    .Emax = 28;
    .BasePrefireAnimTime = 0.5;
    .BaseRecoilAnimTime = 0.2;
    .StaminaRate = 50;
    .attackType = AttackThrowing;
    .weaponType = WeaponThrowing;
    .projectileData = "ThrowingAxeProjectile";
};
datablock ExplosiveData(PotExplosion)
{
    .id = 664;
    .rayNum = 3;
    .radius = 3;
    .hitGroupType[0] = siege;
    .hitGroupDmgLevel[0] = 3.35;
    .emitters[0] = Explosion_fire_small;
    .emitters[1] = Explosion_smoke_small;
    .emitters[2] = Explosion_elements_of_dirt_small;
    .emittersDuration[0] = 4;
    .emittersDuration[1] = 4;
    .emittersDuration[2] = 4;
    .SoundID = 101;
};
datablock ArrowData(ThrowingPotProjectile)
{
    .id = 346;
    .sound = "ThrowingFlySound";
    .stuckArrowLifeTime = 10;
    .projectileShape = "art/models/3d-2d/weapons/ammunition/grenade.dts";
    .upForce = 0;
    .Friction = 0.25;
    .shapeFile = "art/models/3d-2d/weapons/ammunition/sling_ammo_pouch.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .correctMuzzleVector = 0;
    .weaponType = WeaponAmmo;
    .explosionData = "PotExplosion";
};
datablock ThrowingWeaponData(ThrowingPot : BaseThrowing)
{
    .id = 345;
    .Object_typeID = 1104;
    .shapeFile = "art/models/3d-2d/weapons/ammunition/grenade.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .hitGroupType[0] = siege;
    .hitGroupDmgLevel[0] = 0.1;
    .WoundMultiplier = 0.06;
    .FractureMultiplier = 0.095;
    .StunMultiplier = 0;
    .AgilityNeed = 30;
    .StrengthNeed = 40;
    .MaxAccuracy = 1.5;
    .Emax = 25;
    .BasePrefireAnimTime = 0.5;
    .BaseRecoilAnimTime = 0.2;
    .StaminaRate = 40;
    .attackType = AttackThrowing;
    .weaponType = WeaponThrowing;
    .projectileData = "ThrowingPotProjectile";
};
datablock ExplosiveData(FireworkPotExplosion)
{
    .id = 665;
    .rayNum = 4;
    .radius = 3;
    .hitGroupType[0] = siege;
    .hitGroupDmgLevel[0] = 0.1;
    .emitters[0] = spark_star;
    .emitters[1] = Explosion_elements_of_dirt_small;
    .emittersDuration[0] = 4;
    .emittersDuration[1] = 4;
    .SoundID = 101;
};
datablock ArrowData(FireworkPotProjectile)
{
    .id = 592;
    .sound = "ThrowingFlySound";
    .stuckArrowLifeTime = 10;
    .projectileShape = "art/models/3d-2d/weapons/ammunition/grenade.dts";
    .upForce = 0;
    .Friction = 0.25;
    .shapeFile = "art/models/3d-2d/weapons/ammunition/sling_ammo_pouch.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .correctMuzzleVector = 0;
    .weaponType = WeaponAmmo;
    .explosionData = "FireworkPotExplosion";
};
datablock ThrowingWeaponData(FireworkPot : BaseThrowing)
{
    .id = 591;
    .Object_typeID = 1341;
    .shapeFile = "art/models/3d-2d/weapons/ammunition/grenade.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .hitGroupType[0] = siege;
    .hitGroupDmgLevel[0] = 0.1;
    .WoundMultiplier = 0.06;
    .FractureMultiplier = 0.095;
    .StunMultiplier = 0;
    .AgilityNeed = 10;
    .StrengthNeed = 10;
    .MaxAccuracy = 1;
    .Emax = 25;
    .BasePrefireAnimTime = 0.5;
    .BaseRecoilAnimTime = 0.2;
    .StaminaRate = 40;
    .attackType = AttackThrowing;
    .weaponType = WeaponThrowing;
    .projectileData = "FireworkPotProjectile";
};
datablock ExplosiveData(SnowballExplosion)
{
    .id = 666;
    .rayNum = 2;
    .radius = 1;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 0.01;
    .emitters[0] = snowball_dust;
    .emitters[1] = snowball_element;
    .emittersDuration[0] = 4;
    .emittersDuration[1] = 4;
};
datablock ArrowData(SnowballProjectile)
{
    .id = 369;
    .sound = "ThrowingFlySound";
    .stuckArrowLifeTime = 10;
    .projectileShape = "art/models/3d-2d/weapons/ammunition/snowball.dts";
    .upForce = 0;
    .Friction = 0.25;
    .shapeFile = "art/models/3d-2d/weapons/ammunition/sling_ammo_pouch.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .correctMuzzleVector = 0;
    .weaponType = WeaponAmmo;
    .explosionData = "SnowballExplosion";
};
datablock ThrowingWeaponData(Snowball : BaseThrowing)
{
    .id = 368;
    .Object_typeID = 1344;
    .shapeFile = "art/models/3d-2d/weapons/ammunition/snowball.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 0.1;
    .WoundMultiplier = 0.06;
    .FractureMultiplier = 0.095;
    .StunMultiplier = 0;
    .AgilityNeed = 10;
    .StrengthNeed = 10;
    .MaxAccuracy = 1.2;
    .Emax = 25;
    .BasePrefireAnimTime = 0.5;
    .BaseRecoilAnimTime = 0.2;
    .StaminaRate = 40;
    .attackType = AttackThrowing;
    .weaponType = WeaponThrowing;
    .projectileData = "SnowballProjectile";
};

