datablock ShapeBaseImageData(BaseMeleeWeapon)
{
    .local = 1;
    .BasePrefireAnimTime = 1;
    .BaseFireAnimTime = 1;
    .BaseRecoilAnimTime = 1;
    .stateName[0] = "Ready";
    .stateTransitionOnTriggerDown[0] = "PreFire";
    .stateTransitionOnAltTriggerDown[0] = "PreBlocking";
    .stateName[1] = "PreFire";
    .stateFireSubState[1] = PreFire;
    .stateTransitionOnTimeout[1] = "PreFire_onTimeout";
    .stateTransitionOnTriggerUp[1] = "PreFire_onTrigerUp";
    .stateTransitionOnAltTriggerDown[1] = "PreBlocking";
    .stateWaitForTimeout[1] = 0;
    .stateAllowImageChange[1] = 0;
    .stateScript[1] = "onImagePrefire";
    .stateName[2] = "PreFire_onTimeout";
    .stateFireSubState[2] = PreFire;
    .stateTransitionOnTriggerUp[2] = "Fire";
    .stateTransitionOnAltTriggerDown[2] = "PreBlocking";
    .stateAllowImageChange[2] = 0;
    .stateName[3] = "PreFire_onTrigerUp";
    .stateFireSubState[3] = PreFire;
    .stateTransitionOnTimeout[3] = "Fire";
    .stateTransitionOnAltTriggerDown[3] = "FireCancel";
    .stateWaitForTimeout[3] = 0;
    .stateAllowImageChange[3] = 0;
    .stateName[4] = "FireCancel";
    .stateTransitionOnTimeout[4] = "PostFireWait";
    .stateAllowImageChange[4] = 0;
    .stateScript[4] = "onImageFireCancel";
    .stateName[5] = "Fire";
    .stateFireSubState[5] = Fire;
    .stateFire[5] = 1;
    .stateTransitionOnTimeout[5] = "PostFire";
    .stateTransitionOnAltTriggerDown[5] = "FireCancelRecoil";
    .stateWaitForTimeout[5] = 0;
    .stateAllowImageChange[5] = 0;
    .stateScript[5] = "onImageFire";
    .stateName[6] = "FireCancelRecoil";
    .stateTransitionOnTimeout[6] = "PostFire";
    .stateAllowImageChange[6] = 0;
    .stateScript[6] = "onImageFireCancel";
    .stateName[7] = "PostFire";
    .stateFireSubState[7] = Recoil;
    .stateTransitionOnTimeout[7] = "PostFireWait";
    .stateAllowImageChange[7] = 0;
    .stateName[8] = "PostFireWait";
    .stateFireSubState[8] = PostFire;
    .stateTimeoutValue[8] = 0;
    .stateTransitionOnTimeout[8] = "PostFireWaitForTriggerUp";
    .stateAllowImageChange[8] = 0;
    .stateName[9] = "PostFireWaitForTriggerUp";
    .stateTransitionOnTriggerUp[9] = "PostFireWaitForAltTriggerUp";
    .stateAllowImageChange[9] = 0;
    .stateName[10] = "PostFireWaitForAltTriggerUp";
    .stateTransitionOnAltTriggerUp[10] = "Ready";
    .stateAllowImageChange[10] = 0;
    .stateName[11] = "Draw";
    .stateFireSubState[11] = Draw;
    .stateTransitionOnTimeout[11] = "Ready";
    .stateWaitForTimeout[11] = 1;
    .stateAllowImageChange[11] = 0;
    .stateName[12] = "Attach";
    .stateFireSubState[12] = Attached;
    .stateAllowImageChange[12] = 1;
    .stateName[13] = "PreBlocking";
    .stateFireSubState[13] = PreBlocking;
    .stateWaitForTimeout[13] = 1;
    .stateAllowImageChange[13] = 0;
    .stateTransitionOnTimeout[13] = "Blocking";
    .stateName[14] = "Blocking";
    .stateFireSubState[14] = Blocking;
    .stateWaitForTimeout[14] = 0;
    .stateTimeoutValue[14] = 1;
    .stateAllowImageChange[14] = 0;
    .stateTransitionOnTimeout[14] = "PostFireWait";
    .stateTransitionOnAltTriggerUp[14] = "Ready";
    .stateName[15] = "BlockedHit";
    .stateFireSubState[15] = BlockedHit;
    .stateTransitionOnTimeout[15] = "PostFireWait";
    .stateWaitForTimeout[15] = 1;
    .stateAllowImageChange[15] = 0;
    .stateName[16] = "Trickmove";
    .stateFireSubState[16] = Trickmove;
    .stateTransitionOnTimeout[16] = "Ready";
    .stateTransitionOnTriggerDown[16] = "PreFire";
    .stateTransitionOnAltTriggerDown[16] = "PreBlocking";
    .stateWaitForTimeout[16] = 0;
    .stateAllowImageChange[16] = 0;
};
datablock ShapeBaseImageData(BaseShield)
{
    .local = 1;
    .stateName[0] = "Ready";
    .stateTransitionOnAltTriggerDown[0] = "PreBlocking";
    .stateName[1] = "Draw";
    .stateFireSubState[1] = Draw;
    .stateTransitionOnTimeout[1] = "Ready";
    .stateWaitForTimeout[1] = 1;
    .stateAllowImageChange[1] = 0;
    .stateName[5] = "Fire";
    .stateFireSubState[5] = Fire;
    .stateFire[5] = 1;
    .stateTransitionOnTimeout[5] = "Blocking";
    .stateWaitForTimeout[5] = 1;
    .stateAllowImageChange[5] = 0;
    .stateScript[5] = "onImageFire";
    .stateName[6] = "PreBlocking";
    .stateFireSubState[6] = PreBlocking;
    .stateWaitForTimeout[6] = 1;
    .stateAllowImageChange[6] = 0;
    .stateTransitionOnTimeout[6] = "Blocking";
    .stateName[7] = "Blocking";
    .stateFireSubState[7] = Blocking;
    .stateAllowImageChange[7] = 0;
    .stateWaitForTimeout[7] = 0;
    .stateTransitionOnAltTriggerUp[7] = "Ready";
    .stateName[8] = "BlockedHit";
    .stateFireSubState[8] = BlockedHit;
    .stateTransitionOnTimeout[8] = "Blocking";
    .stateAllowImageChange[8] = 0;
    .stateName[9] = "PostFireWaitForTriggerUp";
    .stateTransitionOnTriggerUp[9] = "PostFireWaitForAltTriggerUp";
    .stateAllowImageChange[9] = 0;
    .stateName[10] = "PostFireWaitForAltTriggerUp";
    .stateTransitionOnAltTriggerUp[10] = "Ready";
    .stateAllowImageChange[10] = 0;
    .stateName[12] = "Attach";
    .stateFireSubState[12] = Attached;
    .stateAllowImageChange[12] = 1;
    .stateName[15] = "Trickmove";
    .stateFireSubState[15] = Trickmove;
    .stateTransitionOnTimeout[15] = "Ready";
    .stateTransitionOnTriggerDown[15] = "PreFire";
    .stateWaitForTimeout[15] = 0;
    .stateAllowImageChange[15] = 0;
};
datablock WeaponData(PracticeSword : BaseMeleeWeapon)
{
    .id = 4;
    .Object_typeID = 555;
    .shapeFile = "art/models/3d-2d/weapons/1hswords/practice_sword_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = Weapon1HMace;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 1;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 1;
    .hitDirection[0] = 0;
    .hitDirection[1] = 1;
    .hitDirection[2] = 1;
    .hitDirection[3] = 1;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0.05;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = PracticeSwordItem;
};
datablock WeaponData(NordicSword : BaseMeleeWeapon)
{
    .id = 5;
    .Object_typeID = 556;
    .shapeFile = "art/models/3d-2d/weapons/1hswords/nordic_sword_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = Weapon1HSword;
    .weaponMaterial = Metal;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 3.55;
    .hitGroupType[1] = Slashing;
    .hitGroupDmgLevel[1] = 1.83;
    .hitGroupType[2] = Blunt;
    .hitGroupDmgLevel[2] = 0.5;
    .hitDirection[0] = "0 2";
    .hitDirection[1] = 1;
    .hitDirection[2] = 1;
    .hitDirection[3] = 1;
    .WoundMultiplier = 1;
    .FractureMultiplier = 0.3;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = NordicSwordItem;
    .BasePrefireAnimTime = 1;
    .BaseFireAnimTime = 1;
    .BaseRecoilAnimTime = 1;
};
datablock WeaponData(KnightSword : BaseMeleeWeapon)
{
    .id = 6;
    .Object_typeID = 557;
    .shapeFile = "art/models/3d-2d/weapons/1-2hswords/knight_sword_export_02.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1_2HSword;
    .weaponType = Weapon1_2HSword;
    .weaponMaterial = Metal;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 3.6;
    .hitGroupType[1] = Slashing;
    .hitGroupDmgLevel[1] = 2.08;
    .hitGroupType[2] = Blunt;
    .hitGroupDmgLevel[2] = 0.5;
    .hitDirection[0] = "0 2";
    .hitDirection[1] = 1;
    .hitDirection[2] = 1;
    .hitDirection[3] = 1;
    .WoundMultiplier = 0.7;
    .FractureMultiplier = 0.3;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = KnightSwordItem;
    .BasePrefireAnimTime = 1.1;
    .BaseFireAnimTime = 0.9;
    .BaseRecoilAnimTime = 0.9;
};
datablock WeaponData(LightSaber : BaseMeleeWeapon)
{
    .id = 7;
    .Object_typeID = 558;
    .shapeFile = "art/models/3d-2d/weapons/1hswords/light_saber_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = Weapon1HSword;
    .weaponMaterial = Metal;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 1.16;
    .hitGroupType[1] = Slashing;
    .hitGroupDmgLevel[1] = 1.46;
    .hitDirection[0] = 0;
    .hitDirection[1] = 1;
    .hitDirection[2] = 1;
    .hitDirection[3] = 1;
    .WoundMultiplier = 0.9;
    .FractureMultiplier = 0.3;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = LightSaberItem;
    .BasePrefireAnimTime = 0.9;
    .BaseFireAnimTime = 0.9;
    .BaseRecoilAnimTime = 0.65;
};
datablock WeaponData(Scimitar : BaseMeleeWeapon)
{
    .id = 8;
    .Object_typeID = 559;
    .shapeFile = "art/models/3d-2d/weapons/1hswords/scimitar_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = Weapon1HSword;
    .weaponMaterial = Metal;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 2.9;
    .hitGroupType[1] = Slashing;
    .hitGroupDmgLevel[1] = 2.01;
    .hitGroupType[2] = Blunt;
    .hitGroupDmgLevel[2] = 0.5;
    .hitDirection[0] = "0 2";
    .hitDirection[1] = 1;
    .hitDirection[2] = 1;
    .hitDirection[3] = 1;
    .WoundMultiplier = 1.3;
    .FractureMultiplier = 0.5;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = ScimitarItem;
    .BasePrefireAnimTime = 0.9;
    .BaseFireAnimTime = 1;
    .BaseRecoilAnimTime = 0.8;
};
datablock WeaponData(Falchion : BaseMeleeWeapon)
{
    .id = 9;
    .Object_typeID = 560;
    .shapeFile = "art/models/3d-2d/weapons/1hswords/falchion_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = Weapon1HSword;
    .weaponMaterial = Metal;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 0.92;
    .hitGroupType[1] = Slashing;
    .hitGroupDmgLevel[1] = 1.9;
    .hitGroupType[2] = Blunt;
    .hitGroupDmgLevel[2] = 0.5;
    .hitDirection[0] = "0 2";
    .hitDirection[1] = 1;
    .hitDirection[2] = 1;
    .hitDirection[3] = 1;
    .WoundMultiplier = 1.3;
    .FractureMultiplier = 0.7;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = FalchionItem;
    .BasePrefireAnimTime = 1.1;
    .BaseFireAnimTime = 0.95;
    .BaseRecoilAnimTime = 1.3;
};
datablock WeaponData(PracticeBastard : BaseMeleeWeapon)
{
    .id = 10;
    .Object_typeID = 561;
    .shapeFile = "art/models/3d-2d/weapons/1-2hswords/practice_bastard_sword_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1_2HSword;
    .weaponType = Weapon1_2HSword;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 0.6;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 0.6;
    .hitDirection[0] = 0;
    .hitDirection[1] = 1;
    .hitDirection[2] = 1;
    .hitDirection[3] = 1;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0.05;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = PracticeBastardItem;
};
datablock WeaponData(Estoc : BaseMeleeWeapon)
{
    .id = 11;
    .Object_typeID = 562;
    .shapeFile = "art/models/3d-2d/weapons/1-2hswords/estoc_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack2HSword;
    .weaponType = Weapon2HSword;
    .weaponMaterial = Metal;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 3.7;
    .hitGroupType[1] = Slashing;
    .hitGroupDmgLevel[1] = 0.8;
    .hitGroupType[2] = Blunt;
    .hitGroupDmgLevel[2] = 0.5;
    .hitDirection[0] = "0 2";
    .hitDirection[1] = 1;
    .hitDirection[2] = 1;
    .hitDirection[3] = 1;
    .WoundMultiplier = 1.5;
    .FractureMultiplier = 0.3;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = EstocItem;
    .BasePrefireAnimTime = 0.5;
    .BaseFireAnimTime = 0.8;
    .BaseRecoilAnimTime = 0.8;
};
datablock WeaponData(BastardSword : BaseMeleeWeapon)
{
    .id = 12;
    .Object_typeID = 563;
    .shapeFile = "art/models/3d-2d/weapons/1-2hswords/bastard.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1_2HSword;
    .weaponType = Weapon1_2HSword;
    .weaponMaterial = Metal;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 2.63;
    .hitGroupType[1] = Slashing;
    .hitGroupDmgLevel[1] = 2.35;
    .hitGroupType[2] = Blunt;
    .hitGroupDmgLevel[2] = 0.5;
    .hitDirection[0] = "0 2";
    .hitDirection[1] = 1;
    .hitDirection[2] = 1;
    .hitDirection[3] = 1;
    .WoundMultiplier = 1;
    .FractureMultiplier = 0.5;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = BastardSwordItem;
    .BasePrefireAnimTime = 1.1;
    .BaseFireAnimTime = 1;
    .BaseRecoilAnimTime = 0.9;
};
datablock WeaponData(BigFalchion : BaseMeleeWeapon)
{
    .id = 13;
    .Object_typeID = 564;
    .shapeFile = "art/models/3d-2d/weapons/1-2hswords/bigfalchion.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1_2HSword;
    .weaponType = Weapon1_2HSword;
    .weaponMaterial = Metal;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 1.1;
    .hitGroupType[1] = Slashing;
    .hitGroupDmgLevel[1] = 1.98;
    .hitGroupType[2] = Blunt;
    .hitGroupDmgLevel[2] = 0.5;
    .hitDirection[0] = "0 2";
    .hitDirection[1] = 1;
    .hitDirection[2] = 1;
    .hitDirection[3] = 1;
    .WoundMultiplier = 1.3;
    .FractureMultiplier = 0.7;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = BigFalchionItem;
    .BasePrefireAnimTime = 1.1;
    .BaseFireAnimTime = 0.95;
    .BaseRecoilAnimTime = 1.2;
};
datablock WeaponData(GrossMesser : BaseMeleeWeapon)
{
    .id = 14;
    .Object_typeID = 565;
    .shapeFile = "art/models/3d-2d/weapons/1hswords/grossmesser_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = Weapon1HSword;
    .weaponMaterial = Metal;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 1.6;
    .hitGroupType[1] = Slashing;
    .hitGroupDmgLevel[1] = 1.7;
    .hitGroupType[2] = Blunt;
    .hitGroupDmgLevel[2] = 0.5;
    .hitDirection[0] = "0 2";
    .hitDirection[1] = 1;
    .hitDirection[2] = 1;
    .hitDirection[3] = 1;
    .WoundMultiplier = 1.3;
    .FractureMultiplier = 0.3;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = GrossMesserItem;
    .BasePrefireAnimTime = 1;
    .BaseFireAnimTime = 1;
    .BaseRecoilAnimTime = 1.1;
};
datablock WeaponData(PracticeAxe : BaseMeleeWeapon)
{
    .id = 15;
    .Object_typeID = 566;
    .shapeFile = "art/models/3d-2d/weapons/1haxes/practice_axe_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = Weapon1HAxe;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 1;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 1.1;
    .hitDirection[0] = 0;
    .hitDirection[1] = 1;
    .hitDirection[2] = 1;
    .hitDirection[3] = 1;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0.05;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = PracticeAxeItem;
};
datablock WeaponData(WarAxe : BaseMeleeWeapon)
{
    .id = 16;
    .Object_typeID = 567;
    .shapeFile = "art/models/3d-2d/weapons/1haxes/waraxe.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = Weapon1HAxe;
    .weaponMaterial = Metal;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 0.8;
    .hitGroupType[1] = Chopping;
    .hitGroupDmgLevel[1] = 1.94;
    .hitGroupType[2] = Blunt;
    .hitGroupDmgLevel[2] = 1;
    .hitDirection[0] = 0;
    .hitDirection[1] = "1 2";
    .hitDirection[2] = "1 2";
    .hitDirection[3] = "1 2";
    .WoundMultiplier = 2;
    .FractureMultiplier = 0.9;
    .StunMultiplier = 0.1;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = WarAxeItem;
    .BasePrefireAnimTime = 1;
    .BaseFireAnimTime = 1;
    .BaseRecoilAnimTime = 1.1;
};
datablock WeaponData(BattleAxe : BaseMeleeWeapon)
{
    .id = 17;
    .Object_typeID = 568;
    .shapeFile = "art/models/3d-2d/weapons/1haxes/battleaxe.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = Weapon1HAxe;
    .weaponMaterial = Metal;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 0.8;
    .hitGroupType[1] = Chopping;
    .hitGroupDmgLevel[1] = 2.09;
    .hitGroupType[2] = Blunt;
    .hitGroupDmgLevel[2] = 1;
    .hitDirection[0] = "0 2";
    .hitDirection[1] = "1 2";
    .hitDirection[2] = "1 2";
    .hitDirection[3] = "1 2";
    .WoundMultiplier = 1.8;
    .FractureMultiplier = 0.9;
    .StunMultiplier = 0.05;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = BattleAxeItem;
    .BasePrefireAnimTime = 1;
    .BaseFireAnimTime = 1;
    .BaseRecoilAnimTime = 1.1;
};
datablock WeaponData(NordicAxe : BaseMeleeWeapon)
{
    .id = 18;
    .Object_typeID = 569;
    .shapeFile = "art/models/3d-2d/weapons/1haxes/nordicaxe.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = Weapon1HAxe;
    .weaponMaterial = Metal;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 2.35;
    .hitGroupType[1] = Chopping;
    .hitGroupDmgLevel[1] = 1.74;
    .hitGroupType[2] = Blunt;
    .hitGroupDmgLevel[2] = 1;
    .hitDirection[0] = 0;
    .hitDirection[1] = "1 2";
    .hitDirection[2] = "1 2";
    .hitDirection[3] = "1 2";
    .WoundMultiplier = 1.5;
    .FractureMultiplier = 0.9;
    .StunMultiplier = 0.05;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = NordicAxeItem;
    .BasePrefireAnimTime = 1.1;
    .BaseFireAnimTime = 1;
    .BaseRecoilAnimTime = 1.1;
};
datablock WeaponData(MorningStar : BaseMeleeWeapon)
{
    .id = 19;
    .Object_typeID = 570;
    .shapeFile = "art/models/3d-2d/weapons/1hmaces/morningstar.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = Weapon1HMace;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 1.36;
    .hitGroupType[1] = Piercing;
    .hitGroupDmgLevel[1] = 1.69;
    .hitGroupType[2] = Blunt;
    .hitGroupDmgLevel[2] = 0.5;
    .hitDirection[0] = 0;
    .hitDirection[1] = "1 2";
    .hitDirection[2] = "1 2";
    .hitDirection[3] = "1 2";
    .WoundMultiplier = 1;
    .FractureMultiplier = 0.5;
    .StunMultiplier = 0.2;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = MorningStarItem;
    .BasePrefireAnimTime = 1.1;
    .BaseFireAnimTime = 1.2;
    .BaseRecoilAnimTime = 1.1;
};
datablock WeaponData(FlangedMace : BaseMeleeWeapon)
{
    .id = 20;
    .Object_typeID = 571;
    .shapeFile = "art/models/3d-2d/weapons/1hmaces/flangedmace.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = Weapon1HMace;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 0.8;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 1.79;
    .hitGroupType[2] = Blunt;
    .hitGroupDmgLevel[2] = 0.5;
    .hitDirection[0] = 0;
    .hitDirection[1] = "1 2";
    .hitDirection[2] = "1 2";
    .hitDirection[3] = "1 2";
    .WoundMultiplier = 0.1;
    .FractureMultiplier = 0.7;
    .StunMultiplier = 0.35;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = FlangedMaceItem;
    .BasePrefireAnimTime = 1;
    .BaseFireAnimTime = 1.1;
    .BaseRecoilAnimTime = 1.1;
};
datablock WeaponData(Cudgel : BaseMeleeWeapon)
{
    .id = 21;
    .Object_typeID = 572;
    .shapeFile = "art/models/3d-2d/weapons/1hmaces/cudgel.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = Weapon1HMace;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 0.8;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 1.7;
    .hitDirection[0] = 0;
    .hitDirection[1] = 1;
    .hitDirection[2] = 1;
    .hitDirection[3] = 1;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0.5;
    .StunMultiplier = 0.1;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = CudgelItem;
    .BasePrefireAnimTime = 1;
    .BaseFireAnimTime = 1;
    .BaseRecoilAnimTime = 0.8;
};
datablock WeaponData(WarPick : BaseMeleeWeapon)
{
    .id = 22;
    .Object_typeID = 573;
    .shapeFile = "art/models/3d-2d/weapons/1hmaces/warpick.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = Weapon1HMace;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 0.8;
    .hitGroupType[1] = Piercing;
    .hitGroupDmgLevel[1] = 1.31;
    .hitGroupType[2] = Blunt;
    .hitGroupDmgLevel[2] = 0.5;
    .hitDirection[0] = 0;
    .hitDirection[1] = "1 2";
    .hitDirection[2] = "1 2";
    .hitDirection[3] = "1 2";
    .WoundMultiplier = 1;
    .FractureMultiplier = 0.3;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = WarPickItem;
    .BasePrefireAnimTime = 0.8;
    .BaseFireAnimTime = 0.9;
    .BaseRecoilAnimTime = 1.4;
};
datablock WeaponData(PracticeLongsword : BaseMeleeWeapon)
{
    .id = 23;
    .Object_typeID = 574;
    .shapeFile = "art/models/3d-2d/weapons/2hswords/practice_longsword_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack2HSword;
    .weaponType = Weapon2HSword;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 1;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 0.7;
    .hitDirection[0] = 0;
    .hitDirection[1] = 1;
    .hitDirection[2] = 1;
    .hitDirection[3] = 1;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0.05;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = PracticeLongswordItem;
};
datablock WeaponData(Claymore : BaseMeleeWeapon)
{
    .id = 24;
    .Object_typeID = 575;
    .shapeFile = "art/models/3d-2d/weapons/2hswords/claymore.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack2HSword;
    .weaponType = Weapon2HSword;
    .weaponMaterial = Metal;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 2.9;
    .hitGroupType[1] = Slashing;
    .hitGroupDmgLevel[1] = 1.65;
    .hitGroupType[2] = Blunt;
    .hitGroupDmgLevel[2] = 0.5;
    .hitDirection[0] = "0 2";
    .hitDirection[1] = 1;
    .hitDirection[2] = 1;
    .hitDirection[3] = 1;
    .WoundMultiplier = 1.15;
    .FractureMultiplier = 0.3;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = ClaymoreItem;
    .BasePrefireAnimTime = 1.1;
    .BaseFireAnimTime = 1.1;
    .BaseRecoilAnimTime = 1.2;
};
datablock WeaponData(Zweihaender : BaseMeleeWeapon)
{
    .id = 25;
    .Object_typeID = 576;
    .shapeFile = "art/models/3d-2d/weapons/2hswords/zweihander.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack2HSword;
    .weaponType = Weapon2HSword;
    .weaponMaterial = Metal;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 2.07;
    .hitGroupType[1] = Slashing;
    .hitGroupDmgLevel[1] = 1.6;
    .hitGroupType[2] = Blunt;
    .hitGroupDmgLevel[2] = 0.5;
    .hitDirection[0] = "0 2";
    .hitDirection[1] = 1;
    .hitDirection[2] = 1;
    .hitDirection[3] = 1;
    .WoundMultiplier = 1.1;
    .FractureMultiplier = 0.5;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = ZweihaenderItem;
    .BasePrefireAnimTime = 1.2;
    .BaseFireAnimTime = 1.1;
    .BaseRecoilAnimTime = 1.15;
};
datablock WeaponData(Flamberge : BaseMeleeWeapon)
{
    .id = 26;
    .Object_typeID = 577;
    .shapeFile = "art/models/3d-2d/weapons/2hswords/flamberge.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack2HSword;
    .weaponType = Weapon2HSword;
    .weaponMaterial = Metal;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 1.55;
    .hitGroupType[1] = Slashing;
    .hitGroupDmgLevel[1] = 1.62;
    .hitGroupType[2] = Blunt;
    .hitGroupDmgLevel[2] = 0.5;
    .hitDirection[0] = "0 2";
    .hitDirection[1] = 1;
    .hitDirection[2] = 1;
    .hitDirection[3] = 1;
    .WoundMultiplier = 1.5;
    .FractureMultiplier = 0.7;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = FlambergeItem;
    .BasePrefireAnimTime = 1.2;
    .BaseFireAnimTime = 1.1;
    .BaseRecoilAnimTime = 1.15;
};
datablock WeaponData(PracticeGreataxe : BaseMeleeWeapon)
{
    .id = 27;
    .Object_typeID = 578;
    .shapeFile = "art/models/3d-2d/weapons/2haxes/practice_greataxe_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack2HWeapon;
    .weaponType = Weapon2HAxe;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 0.7;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 0.5;
    .hitGroupType[2] = Blunt;
    .hitGroupDmgLevel[2] = 0.5;
    .hitDirection[0] = 0;
    .hitDirection[1] = "1 2";
    .hitDirection[2] = "1 2";
    .hitDirection[3] = "1 2";
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0.05;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = PracticeGreataxeItem;
};
datablock WeaponData(Pollaxe : BaseMeleeWeapon)
{
    .id = 28;
    .Object_typeID = 579;
    .shapeFile = "art/models/3d-2d/weapons/polearms/pollaxe.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack2HWeapon;
    .weaponType = WeaponPolearm;
    .weaponMaterial = Metal;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 1.85;
    .hitGroupType[1] = Chopping;
    .hitGroupDmgLevel[1] = 1.4;
    .hitGroupType[2] = Blunt;
    .hitGroupDmgLevel[2] = 1;
    .hitGroupType[3] = Blunt;
    .hitGroupDmgLevel[3] = 0.5;
    .hitDirection[0] = "0 3";
    .hitDirection[1] = "1 3";
    .hitDirection[2] = "1 3";
    .hitDirection[3] = "1 3";
    .WoundMultiplier = 0.7;
    .FractureMultiplier = 0.8;
    .StunMultiplier = 0.21;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = PollaxeItem;
    .BasePrefireAnimTime = 1.1;
    .BaseFireAnimTime = 1;
    .BaseRecoilAnimTime = 1.1;
};
datablock WeaponData(Bardiche : BaseMeleeWeapon)
{
    .id = 29;
    .Object_typeID = 580;
    .shapeFile = "art/models/3d-2d/weapons/2haxes/bardiche.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack2HWeapon;
    .weaponType = Weapon2HAxe;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 0.96;
    .hitGroupType[1] = Chopping;
    .hitGroupDmgLevel[1] = 1.5;
    .hitGroupType[2] = Blunt;
    .hitGroupDmgLevel[2] = 0.5;
    .hitGroupType[3] = Blunt;
    .hitGroupDmgLevel[3] = 0.5;
    .hitDirection[0] = "0 3";
    .hitDirection[1] = "1 2";
    .hitDirection[2] = "1 2";
    .hitDirection[3] = "1 2";
    .WoundMultiplier = 1;
    .FractureMultiplier = 0.7;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = BardicheItem;
    .BasePrefireAnimTime = 1.2;
    .BaseFireAnimTime = 1;
    .BaseRecoilAnimTime = 1.7;
};
datablock WeaponData(BroadAxe : BaseMeleeWeapon)
{
    .id = 30;
    .Object_typeID = 581;
    .shapeFile = "art/models/3d-2d/weapons/2haxes/broad_axe.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack2HWeapon;
    .weaponType = Weapon2HAxe;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 0.72;
    .hitGroupType[1] = Chopping;
    .hitGroupDmgLevel[1] = 1.6;
    .hitGroupType[2] = Blunt;
    .hitGroupDmgLevel[2] = 0.5;
    .hitGroupType[3] = Blunt;
    .hitGroupDmgLevel[3] = 0.5;
    .hitDirection[0] = "0 3";
    .hitDirection[1] = "1 2";
    .hitDirection[2] = "1 2";
    .hitDirection[3] = "1 2";
    .WoundMultiplier = 0.8;
    .FractureMultiplier = 0.8;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = BroadAxeItem;
    .BasePrefireAnimTime = 1.1;
    .BaseFireAnimTime = 1.1;
    .BaseRecoilAnimTime = 1.8;
};
datablock WeaponData(SledgeHammer : BaseMeleeWeapon)
{
    .id = 31;
    .Object_typeID = 582;
    .shapeFile = "art/models/3d-2d/weapons/2hmaces/sledgehammer.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack2HWeapon;
    .weaponType = Weapon2HMace;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 1.28;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 2;
    .hitGroupType[2] = Blunt;
    .hitGroupDmgLevel[2] = 0.5;
    .hitGroupType[3] = Blunt;
    .hitGroupDmgLevel[3] = 0.5;
    .hitDirection[0] = "0 3";
    .hitDirection[1] = "1 2";
    .hitDirection[2] = "1 2";
    .hitDirection[3] = "1 2";
    .WoundMultiplier = 0;
    .FractureMultiplier = 0.9;
    .StunMultiplier = 0.35;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = SledgeHammerItem;
    .BasePrefireAnimTime = 1.3;
    .BaseFireAnimTime = 1.1;
    .BaseRecoilAnimTime = 1.5;
};
datablock WeaponData(Maul : BaseMeleeWeapon)
{
    .id = 32;
    .Object_typeID = 583;
    .shapeFile = "art/models/3d-2d/weapons/2hmaces/maul.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack2HWeapon;
    .weaponType = Weapon2HMace;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 1.28;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 2.07;
    .hitGroupType[2] = Blunt;
    .hitGroupDmgLevel[2] = 0.5;
    .hitGroupType[3] = Blunt;
    .hitGroupDmgLevel[3] = 0.5;
    .hitDirection[0] = "0 3";
    .hitDirection[1] = "1 2";
    .hitDirection[2] = "1 2";
    .hitDirection[3] = "1 2";
    .WoundMultiplier = 0;
    .FractureMultiplier = 0.8;
    .StunMultiplier = 0.4;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = MaulItem;
    .BasePrefireAnimTime = 1.3;
    .BaseFireAnimTime = 1.2;
    .BaseRecoilAnimTime = 1.6;
};
datablock WeaponData(PracticeMaul : BaseMeleeWeapon)
{
    .id = 33;
    .Object_typeID = 584;
    .shapeFile = "art/models/3d-2d/weapons/2hmaces/practice_maul_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack2HWeapon;
    .weaponType = Weapon2HMace;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 1;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 0.8;
    .hitGroupType[2] = Blunt;
    .hitGroupDmgLevel[2] = 0.5;
    .hitDirection[0] = 0;
    .hitDirection[1] = "1 2";
    .hitDirection[2] = "1 2";
    .hitDirection[3] = "1 2";
    .WoundMultiplier = 0;
    .FractureMultiplier = 0.1;
    .StunMultiplier = 0.05;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = PracticeMaulItem;
    .BasePrefireAnimTime = 1.2;
    .BaseFireAnimTime = 1;
    .BaseRecoilAnimTime = 1.2;
};
datablock WeaponData(Glaive : BaseMeleeWeapon)
{
    .id = 34;
    .Object_typeID = 585;
    .shapeFile = "art/models/3d-2d/weapons/polearms/glaive.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack2HWeapon;
    .weaponType = WeaponPolearm;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 1.28;
    .hitGroupType[1] = Slashing;
    .hitGroupDmgLevel[1] = 1.52;
    .hitGroupType[2] = Blunt;
    .hitGroupDmgLevel[2] = 0.5;
    .hitGroupType[3] = Blunt;
    .hitGroupDmgLevel[3] = 0.5;
    .hitDirection[0] = "0 3";
    .hitDirection[1] = "1 2";
    .hitDirection[2] = "1 2";
    .hitDirection[3] = "1 2";
    .WoundMultiplier = 0.7;
    .FractureMultiplier = 0.4;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = GlaiveItem;
    .BasePrefireAnimTime = 1.2;
    .BaseFireAnimTime = 1.1;
    .BaseRecoilAnimTime = 1.1;
};
datablock WeaponData(Guisarme : BaseMeleeWeapon)
{
    .id = 35;
    .Object_typeID = 586;
    .shapeFile = "art/models/3d-2d/weapons/polearms/guisarme.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack2HWeapon;
    .weaponType = WeaponPolearm;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 2.16;
    .hitGroupType[1] = Slashing;
    .hitGroupDmgLevel[1] = 1.48;
    .hitGroupType[2] = Blunt;
    .hitGroupDmgLevel[2] = 0.5;
    .hitGroupType[3] = Blunt;
    .hitGroupDmgLevel[3] = 0.5;
    .hitDirection[0] = "0 3";
    .hitDirection[1] = "1 2";
    .hitDirection[2] = "1 2";
    .hitDirection[3] = "1 2";
    .WoundMultiplier = 0.7;
    .FractureMultiplier = 0.1;
    .StunMultiplier = 0.2;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = GuisarmeItem;
    .BasePrefireAnimTime = 1;
    .BaseFireAnimTime = 1;
    .BaseRecoilAnimTime = 1.1;
};
datablock WeaponData(WarScythe : BaseMeleeWeapon)
{
    .id = 36;
    .Object_typeID = 587;
    .shapeFile = "art/models/3d-2d/weapons/polearms/warscythe.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack2HWeapon;
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 1.12;
    .hitGroupType[1] = Slashing;
    .hitGroupDmgLevel[1] = 1.47;
    .hitGroupType[2] = Blunt;
    .hitGroupDmgLevel[2] = 0.5;
    .hitGroupType[3] = Blunt;
    .hitGroupDmgLevel[3] = 0.5;
    .hitDirection[0] = "0 3";
    .hitDirection[1] = "1 2";
    .hitDirection[2] = "1 2";
    .hitDirection[3] = "1 2";
    .WoundMultiplier = 0.5;
    .FractureMultiplier = 0.2;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = WarScytheItem;
    .BasePrefireAnimTime = 1.1;
    .BaseFireAnimTime = 1.1;
    .BaseRecoilAnimTime = 1.1;
};
datablock WeaponData(Pitchfork : BaseMeleeWeapon)
{
    .id = 37;
    .Object_typeID = 588;
    .shapeFile = "art/models/3d-2d/tools/pitchfork.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack2HWeapon;
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 1.6;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 0.88;
    .hitDirection[0] = "0 1";
    .hitDirection[1] = 1;
    .hitDirection[2] = 1;
    .hitDirection[3] = 1;
    .WoundMultiplier = 0.8;
    .FractureMultiplier = 0.3;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = PitchforkItem;
    .BasePrefireAnimTime = 1;
    .BaseFireAnimTime = 1;
    .BaseRecoilAnimTime = 1;
};
datablock WeaponData(Partisan : BaseMeleeWeapon)
{
    .id = 38;
    .Object_typeID = 589;
    .shapeFile = "art/models/3d-2d/weapons/polearms/partisan_export_02.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack2HWeapon;
    .weaponType = WeaponPolearm;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 2.05;
    .hitGroupType[1] = Slashing;
    .hitGroupDmgLevel[1] = 1.31;
    .hitGroupType[2] = Blunt;
    .hitGroupDmgLevel[2] = 0.5;
    .hitDirection[0] = "0 2";
    .hitDirection[1] = "1 2";
    .hitDirection[2] = "1 2";
    .hitDirection[3] = "1 2";
    .WoundMultiplier = 0.8;
    .FractureMultiplier = 0.2;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = PartisanItem;
    .BasePrefireAnimTime = 1;
    .BaseFireAnimTime = 1;
    .BaseRecoilAnimTime = 1.1;
};
datablock WeaponData(Staff : BaseMeleeWeapon)
{
    .id = 39;
    .Object_typeID = 590;
    .shapeFile = "art/models/3d-2d/weapons/polearms/staff.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack2HWeapon;
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 1.2;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 1.2;
    .hitDirection[0] = 0;
    .hitDirection[1] = 1;
    .hitDirection[2] = 1;
    .hitDirection[3] = 1;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0.5;
    .StunMultiplier = 0.05;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = StaffItem;
    .BasePrefireAnimTime = 1.1;
    .BaseFireAnimTime = 1.1;
    .BaseRecoilAnimTime = 1;
};
datablock WeaponData(Spear : BaseMeleeWeapon)
{
    .id = 40;
    .Object_typeID = 591;
    .shapeFile = "art/models/3d-2d/weapons/spears/spear_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = AttackSpear;
    .weaponType = WeaponSpear;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 3.36;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 0.56;
    .hitDirection[0] = "0 1";
    .hitDirection[1] = 1;
    .hitDirection[2] = 1;
    .hitDirection[3] = 1;
    .WoundMultiplier = 1;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = SpearItem;
    .BasePrefireAnimTime = 0.8;
    .BaseFireAnimTime = 0.8;
    .BaseRecoilAnimTime = 0.8;
};
datablock WeaponData(BoarSpear : BaseMeleeWeapon)
{
    .id = 41;
    .Object_typeID = 592;
    .shapeFile = "art/models/3d-2d/weapons/spears/boar_spear_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = AttackSpear;
    .weaponType = WeaponSpear;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 3.52;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 0.56;
    .hitDirection[0] = "0 1";
    .hitDirection[1] = 1;
    .hitDirection[2] = 1;
    .hitDirection[3] = 1;
    .WoundMultiplier = 1.3;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = BoarSpearItem;
    .BasePrefireAnimTime = 0.8;
    .BaseFireAnimTime = 0.7;
    .BaseRecoilAnimTime = 1.1;
};
datablock WeaponData(AwlPike : BaseMeleeWeapon)
{
    .id = 42;
    .Object_typeID = 593;
    .shapeFile = "art/models/3d-2d/weapons/spears/ahlspiess_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = AttackSpear;
    .weaponType = WeaponSpear;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 4.27;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 0.64;
    .hitDirection[0] = "0 1";
    .hitDirection[1] = 1;
    .hitDirection[2] = 1;
    .hitDirection[3] = 1;
    .WoundMultiplier = 1.2;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = AwlPikeItem;
    .BasePrefireAnimTime = 1;
    .BaseFireAnimTime = 0.8;
    .BaseRecoilAnimTime = 0.8;
};
datablock WeaponData(BecdeCorbin : BaseMeleeWeapon)
{
    .id = 43;
    .Object_typeID = 594;
    .shapeFile = "art/models/3d-2d/weapons/spears/bec_de_corbin_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack2HWeapon;
    .weaponType = WeaponSpear;
    .weaponMaterial = Metal;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 2.2;
    .hitGroupType[1] = Piercing;
    .hitGroupDmgLevel[1] = 1.37;
    .hitGroupType[2] = Blunt;
    .hitGroupDmgLevel[2] = 0.5;
    .hitDirection[0] = "0 2";
    .hitDirection[1] = "1 2";
    .hitDirection[2] = "1 2";
    .hitDirection[3] = "1 2";
    .WoundMultiplier = 0.8;
    .FractureMultiplier = 0;
    .StunMultiplier = 0.05;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = BecdeCorbinItem;
    .BasePrefireAnimTime = 1;
    .BaseFireAnimTime = 1;
    .BaseRecoilAnimTime = 1;
};
datablock WeaponData(ShortPike : BaseMeleeWeapon)
{
    .id = 44;
    .Object_typeID = 595;
    .shapeFile = "art/models/3d-2d/weapons/pikes/short_pike_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = AttackPike;
    .weaponType = WeaponPike;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 3.1;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 0.5;
    .hitDirection[0] = 0;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 2;
    .FractureMultiplier = 0;
    .StunMultiplier = 0.3;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = ShortPikeItem;
    .BasePrefireAnimTime = 0.7;
    .BaseFireAnimTime = 3;
    .BaseRecoilAnimTime = 0.9;
    .stateTransitionOnAltTriggerDown[0] = "";
    .stateTransitionOnAltTriggerDown[1] = "FireCancel";
    .stateTransitionOnAltTriggerDown[2] = "FireCancel";
    .stateTransitionOnAltTriggerDown[16] = "";
};
datablock WeaponData(MediumPike : BaseMeleeWeapon)
{
    .id = 45;
    .Object_typeID = 596;
    .shapeFile = "art/models/3d-2d/weapons/pikes/medium_pike_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = AttackPike;
    .weaponType = WeaponPike;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 3.1;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 0.5;
    .hitDirection[0] = 0;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 2;
    .FractureMultiplier = 0;
    .StunMultiplier = 0.35;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = MediumPikeItem;
    .BasePrefireAnimTime = 0.85;
    .BaseFireAnimTime = 3;
    .BaseRecoilAnimTime = 1;
    .stateTransitionOnAltTriggerDown[0] = "";
    .stateTransitionOnAltTriggerDown[1] = "FireCancel";
    .stateTransitionOnAltTriggerDown[2] = "FireCancel";
    .stateTransitionOnAltTriggerDown[16] = "";
};
datablock WeaponData(LongPike : BaseMeleeWeapon)
{
    .id = 46;
    .Object_typeID = 597;
    .shapeFile = "art/models/3d-2d/weapons/pikes/long_pike_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = AttackPike;
    .weaponType = WeaponPike;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 3.1;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 0.5;
    .hitDirection[0] = 0;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 2;
    .FractureMultiplier = 0;
    .StunMultiplier = 0.4;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = LongPikeItem;
    .BasePrefireAnimTime = 1;
    .BaseFireAnimTime = 3;
    .BaseRecoilAnimTime = 1;
    .stateTransitionOnAltTriggerDown[0] = "";
    .stateTransitionOnAltTriggerDown[1] = "FireCancel";
    .stateTransitionOnAltTriggerDown[2] = "FireCancel";
    .stateTransitionOnAltTriggerDown[16] = "";
};
datablock WeaponData(Lance : BaseMeleeWeapon)
{
    .id = 47;
    .Object_typeID = 598;
    .shapeFile = "art/models/3d-2d/weapons/lances/lance_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = AttackPike;
    .weaponType = WeaponLance;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 2.8;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 0.5;
    .hitDirection[0] = "0 1";
    .hitDirection[1] = 1;
    .hitDirection[2] = 1;
    .hitDirection[3] = 1;
    .WoundMultiplier = 1;
    .FractureMultiplier = 0;
    .StunMultiplier = 0.25;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = LanceItem;
    .BasePrefireAnimTime = 1.2;
    .BaseFireAnimTime = 3;
    .BaseRecoilAnimTime = 1;
    .stateCheckTransition[1] = 1;
    .stateTransitionOnAltTriggerDown[0] = "";
    .stateTransitionOnAltTriggerDown[1] = "FireCancel";
    .stateTransitionOnAltTriggerDown[2] = "FireCancel";
    .stateTransitionOnAltTriggerDown[16] = "";
};
datablock WeaponData(JoustingLance : BaseMeleeWeapon)
{
    .id = 48;
    .Object_typeID = 599;
    .shapeFile = "art/models/3d-2d/weapons/lances/jousting_lance_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = AttackPike;
    .weaponType = WeaponLance;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 2.65;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 0.5;
    .hitDirection[0] = "0 1";
    .hitDirection[1] = 1;
    .hitDirection[2] = 1;
    .hitDirection[3] = 1;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0.3;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = JoustingLanceItem;
    .BasePrefireAnimTime = 1;
    .BaseFireAnimTime = 3;
    .BaseRecoilAnimTime = 0.8;
    .stateCheckTransition[1] = 1;
    .stateTransitionOnAltTriggerDown[0] = "";
    .stateTransitionOnAltTriggerDown[1] = "FireCancel";
    .stateTransitionOnAltTriggerDown[2] = "FireCancel";
    .stateTransitionOnAltTriggerDown[16] = "";
};
datablock ShieldData(TargeShield : BaseShield)
{
    .id = 70;
    .Object_typeID = 612;
    .shapeFile = "art/models/3d-2d/armors/shields/shield_woodenround.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = WeaponShield;
    .hitDirection[0] = 0;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = TargeShieldItem;
};
datablock ShieldData(PrimitiveShield : BaseShield)
{
    .id = 71;
    .Object_typeID = 613;
    .shapeFile = "art/models/3d-2d/armors/shields/shield_primitive.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = WeaponShield;
    .hitDirection[0] = 0;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = PrimitiveShieldItem;
};
datablock ShieldData(BucklerShield : BaseShield)
{
    .id = 72;
    .Object_typeID = 614;
    .shapeFile = "art/models/3d-2d/armors/shields/buckler_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = WeaponShield;
    .hitDirection[0] = 0;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = BucklerShieldItem;
};
datablock ShieldData(HeaterShield : BaseShield)
{
    .id = 73;
    .Object_typeID = 615;
    .shapeFile = "art/models/3d-2d/armors/shields/shield_heaterb.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = WeaponShield;
    .hitDirection[0] = 0;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = HeaterShieldItem;
};
datablock ShieldData(KiteShield : BaseShield)
{
    .id = 74;
    .Object_typeID = 616;
    .shapeFile = "art/models/3d-2d/armors/shields/shield_kite.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = WeaponShield;
    .hitDirection[0] = 0;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = KiteShieldItem;
};
datablock ShieldData(TowerShield : BaseShield)
{
    .id = 75;
    .Object_typeID = 617;
    .shapeFile = "art/models/3d-2d/armors/shields/shield_tower.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = WeaponShield;
    .hitDirection[0] = 0;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = TowerShieldItem;
};
datablock ShieldData(PaviseShield : BaseShield)
{
    .id = 76;
    .Object_typeID = 618;
    .shapeFile = "art/models/3d-2d/armors/shields/shield_pavise.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = WeaponShield;
    .hitDirection[0] = 0;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = PaviseShieldItem;
};
datablock WeaponData(Shovel : BaseMeleeWeapon)
{
    .id = 120;
    .Object_typeID = 40;
    .shapeFile = "art/models/3d-2d/tools/shovel.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack2HWeapon;
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Slashing;
    .hitGroupDmgLevel[0] = 1;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 1;
    .hitDirection[0] = 0;
    .hitDirection[1] = 1;
    .hitDirection[2] = 1;
    .hitDirection[3] = 1;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = ShovelItem;
};
datablock WeaponData(Primitive_shovel : BaseMeleeWeapon)
{
    .id = 121;
    .Object_typeID = 41;
    .shapeFile = "art/models/3d-2d/tools/primitive_shovel.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack2HWeapon;
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 1;
    .hitDirection[0] = 0;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = Primitive_shovelItem;
};
datablock WeaponData(Primitive_pickaxe : BaseMeleeWeapon)
{
    .id = 122;
    .Object_typeID = 47;
    .shapeFile = "art/models/3d-2d/tools/primitivepickaxe_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack2HSword;
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 1;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 1;
    .hitDirection[0] = 1;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = Primitive_pickaxeItem;
};
datablock WeaponData(Pickaxe : BaseMeleeWeapon)
{
    .id = 123;
    .Object_typeID = 48;
    .shapeFile = "art/models/3d-2d/tools/pickaxe_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack2HSword;
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 1.1;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 1;
    .hitDirection[0] = 1;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = PickaxeItem;
};
datablock WeaponData(Hardened_steel_pickaxe : BaseMeleeWeapon)
{
    .id = 124;
    .Object_typeID = 49;
    .shapeFile = "art/models/3d-2d/tools/steelpickaxe_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack2HSword;
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 1.2;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 1;
    .hitDirection[0] = 1;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = Hardened_steel_pickaxeItem;
};
datablock WeaponData(Primitive_hammer : BaseMeleeWeapon)
{
    .id = 125;
    .Object_typeID = 43;
    .shapeFile = "art/models/3d-2d/tools/primitive_hammer.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 1;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 1;
    .hitDirection[0] = 1;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = Primitive_hammerItem;
};
datablock WeaponData(Smiths_Hammer : BaseMeleeWeapon)
{
    .id = 126;
    .Object_typeID = 42;
    .shapeFile = "art/models/3d-2d/tools/blacksmithhammer_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 1;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 1;
    .hitDirection[0] = 1;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = Smiths_HammerItem;
};
datablock WeaponData(Mallet : BaseMeleeWeapon)
{
    .id = 127;
    .Object_typeID = 44;
    .shapeFile = "art/models/3d-2d/tools/mallet_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 1;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 1;
    .hitDirection[0] = 1;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = MalletItem;
};
datablock WeaponData(Fishing_Pole : BaseMeleeWeapon)
{
    .id = 128;
    .Object_typeID = 621;
    .shapeFile = "art/models/3d-2d/tools/fishingrod_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack2HWeapon;
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 0.7;
    .hitDirection[0] = 0;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = Fishing_PoleItem;
    .BasePrefireAnimTime = 1.2;
    .BaseFireAnimTime = 1.2;
    .BaseRecoilAnimTime = 1.2;
};
datablock WeaponData(Primitive_Axe : BaseMeleeWeapon)
{
    .id = 129;
    .Object_typeID = 45;
    .shapeFile = "art/models/3d-2d/tools/primitive_axe.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Slashing;
    .hitGroupDmgLevel[0] = 1;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 1;
    .hitDirection[0] = 1;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = Primitive_AxeItem;
};
datablock WeaponData(Hatchet : BaseMeleeWeapon)
{
    .id = 130;
    .Object_typeID = 46;
    .shapeFile = "art/models/3d-2d/tools/hatchet_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Slashing;
    .hitGroupDmgLevel[0] = 1.2;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 1;
    .hitDirection[0] = 1;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = HatchetItem;
};
datablock WeaponData(Primitive_Saw : BaseMeleeWeapon)
{
    .id = 131;
    .Object_typeID = 50;
    .shapeFile = "art/models/3d-2d/tools/primitivesaw_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 1;
    .hitDirection[0] = 0;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = Primitive_SawItem;
};
datablock WeaponData(Saw : BaseMeleeWeapon)
{
    .id = 132;
    .Object_typeID = 51;
    .shapeFile = "art/models/3d-2d/tools/saw_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 1;
    .hitDirection[0] = 0;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = SawItem;
};
datablock WeaponData(Primitive_CrucibleandStick : BaseMeleeWeapon)
{
    .id = 133;
    .Object_typeID = 463;
    .shapeFile = "art/models/3d-2d/tools/primitivecas_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 0.5;
    .hitDirection[0] = 0;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = Primitive_CrucibleandStickItem;
};
datablock WeaponData(CrucibleandTongs : BaseMeleeWeapon)
{
    .id = 134;
    .Object_typeID = 464;
    .shapeFile = "art/models/3d-2d/tools/cas_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 0.7;
    .hitDirection[0] = 0;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = CrucibleandTongsItem;
};
datablock WeaponData(Primitive_Sickle : BaseMeleeWeapon)
{
    .id = 135;
    .Object_typeID = 30;
    .shapeFile = "art/models/3d-2d/tools/primitive_sickle.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Slashing;
    .hitGroupDmgLevel[0] = 1;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 1;
    .hitDirection[0] = 1;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = Primitive_SickleItem;
};
datablock WeaponData(Sickle : BaseMeleeWeapon)
{
    .id = 136;
    .Object_typeID = 33;
    .shapeFile = "art/models/3d-2d/tools/sickle_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = WeaponMisc;
    .weaponMaterial = Metal;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 1.2;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 1;
    .hitDirection[0] = 1;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = SickleItem;
};
datablock ShieldData(IronRoundShield : BaseShield)
{
    .id = 147;
    .Object_typeID = 1066;
    .shapeFile = "art/models/3d-2d/armors/shields/shield_steelround.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = WeaponShield;
    .hitDirection[0] = 0;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = IronRoundShieldItem;
};
datablock WeaponData(Primitive_Cooking_Pot : BaseMeleeWeapon)
{
    .id = 319;
    .Object_typeID = 1028;
    .shapeFile = "art/models/3d-2d/tools/primitivecookingpot_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 0.5;
    .hitDirection[0] = 0;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = Primitive_Cooking_PotItem;
};
datablock WeaponData(Cooking_Pot : BaseMeleeWeapon)
{
    .id = 320;
    .Object_typeID = 1029;
    .shapeFile = "art/models/3d-2d/tools/cookingpot_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 0.8;
    .hitDirection[0] = 0;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = Cooking_PotItem;
};
datablock WeaponData(Primitive_Knife : BaseMeleeWeapon)
{
    .id = 321;
    .Object_typeID = 289;
    .shapeFile = "art/models/3d-2d/tools/primitive_knife.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 1;
    .hitGroupType[1] = Slashing;
    .hitGroupDmgLevel[1] = 1;
    .hitDirection[0] = 0;
    .hitDirection[1] = 1;
    .hitDirection[2] = 1;
    .hitDirection[3] = 1;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = Primitive_KnifeItem;
};
datablock WeaponData(Knife : BaseMeleeWeapon)
{
    .id = 322;
    .Object_typeID = 290;
    .shapeFile = "art/models/3d-2d/tools/simpleknife_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = WeaponMisc;
    .weaponMaterial = Metal;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 1.9;
    .hitGroupType[1] = Slashing;
    .hitGroupDmgLevel[1] = 1.2;
    .hitDirection[0] = 0;
    .hitDirection[1] = 1;
    .hitDirection[2] = 1;
    .hitDirection[3] = 1;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = KnifeItem;
};
datablock WeaponData(Skinning_knife : BaseMeleeWeapon)
{
    .id = 323;
    .Object_typeID = 291;
    .shapeFile = "art/models/3d-2d/tools/heavyknife_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = WeaponMisc;
    .weaponMaterial = Metal;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 1.9;
    .hitGroupType[1] = Slashing;
    .hitGroupDmgLevel[1] = 1.2;
    .hitDirection[0] = 0;
    .hitDirection[1] = 1;
    .hitDirection[2] = 1;
    .hitDirection[3] = 1;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = Skinning_knifeItem;
};
datablock WeaponData(Glassblower_toolkit : BaseMeleeWeapon)
{
    .id = 324;
    .Object_typeID = 294;
    .shapeFile = "art/models/3d-2d/tools/gstick_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack2HWeapon;
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 1;
    .hitDirection[0] = 0;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = Glassblower_toolkitItem;
};
datablock WeaponData(Bear_Paw)
{
    .id = 325;
    .shapeFile = "";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Slashing;
    .hitGroupDmgLevel[0] = 0.5;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 2;
    .hitDirection[0] = 0;
    .hitDirection[1] = 1;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0.5;
    .FractureMultiplier = 0.1;
    .StunMultiplier = 0.05;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = Bear_PawItem;
};
datablock WeaponData(Wild_Horse_Hoof)
{
    .id = 326;
    .shapeFile = "";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 0.5;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 1;
    .hitDirection[0] = 0;
    .hitDirection[1] = 1;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0.5;
    .StunMultiplier = 0.1;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = Wild_Horse_HoofItem;
};
datablock WeaponData(Deer_Hoof)
{
    .id = 327;
    .shapeFile = "";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 0.4;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 0.8;
    .hitDirection[0] = 0;
    .hitDirection[1] = 1;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0.5;
    .StunMultiplier = 0.1;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = Deer_HoofItem;
};
datablock WeaponData(Hind_Hoof)
{
    .id = 328;
    .shapeFile = "";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 0.4;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 0.8;
    .hitDirection[0] = 0;
    .hitDirection[1] = 1;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0.5;
    .StunMultiplier = 0.1;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = Hind_HoofItem;
};
datablock WeaponData(Wolf_Fang)
{
    .id = 329;
    .shapeFile = "";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Slashing;
    .hitGroupDmgLevel[0] = 0.3;
    .hitGroupType[1] = Slashing;
    .hitGroupDmgLevel[1] = 0.5;
    .hitDirection[0] = 0;
    .hitDirection[1] = 1;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0.5;
    .FractureMultiplier = 0.2;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = Wolf_FangItem;
};
datablock WeaponData(Moose_Hoof)
{
    .id = 330;
    .shapeFile = "";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 0.5;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 1;
    .hitDirection[0] = 0;
    .hitDirection[1] = 1;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0.5;
    .StunMultiplier = 0.3;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = Moose_HoofItem;
};
datablock WeaponData(Boar_Tusk)
{
    .id = 331;
    .shapeFile = "";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 0.3;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 0.5;
    .hitDirection[0] = 0;
    .hitDirection[1] = 1;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0.4;
    .FractureMultiplier = 0.2;
    .StunMultiplier = 0.1;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = Boar_TuskItem;
};
datablock WeaponData(Sow_Tusk)
{
    .id = 332;
    .shapeFile = "";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 0.2;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 0.4;
    .hitDirection[0] = 0;
    .hitDirection[1] = 1;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0.2;
    .FractureMultiplier = 0.1;
    .StunMultiplier = 0.05;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = Sow_TuskItem;
};
datablock WeaponData(Mutton_Horns)
{
    .id = 333;
    .shapeFile = "";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 0.4;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 0.7;
    .hitDirection[0] = 0;
    .hitDirection[1] = 1;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0.4;
    .StunMultiplier = 0.1;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = Mutton_HornsItem;
};
datablock WeaponData(Bull_Horns)
{
    .id = 334;
    .shapeFile = "";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 0.8;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 1.6;
    .hitDirection[0] = 0;
    .hitDirection[1] = 1;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0.6;
    .StunMultiplier = 0.3;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = Bull_HornsItem;
};
datablock WeaponData(Cow_Horns)
{
    .id = 335;
    .shapeFile = "";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 0.7;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 1.5;
    .hitDirection[0] = 0;
    .hitDirection[1] = 1;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0.3;
    .StunMultiplier = 0.1;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = Cow_HornsItem;
};
datablock WeaponData(Primitive_Fishing_Pole : BaseMeleeWeapon)
{
    .id = 336;
    .Object_typeID = 620;
    .shapeFile = "art/models/3d-2d/tools/fishingrod_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack2HWeapon;
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 0.7;
    .hitDirection[0] = 0;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = Primitive_Fishing_PoleItem;
    .BasePrefireAnimTime = 1.2;
    .BaseFireAnimTime = 1.2;
    .BaseRecoilAnimTime = 1.2;
};
datablock WeaponData(Torch : BaseMeleeWeapon)
{
    .id = 337;
    .Object_typeID = 38;
    .shapeFile = "art/models/3d-2d/tools/torch.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack2HWeapon;
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = siege;
    .hitGroupDmgLevel[0] = 0.1;
    .hitGroupType[1] = siege;
    .hitGroupDmgLevel[1] = 0.1;
    .hitDirection[0] = 0;
    .hitDirection[1] = 1;
    .hitDirection[2] = 1;
    .hitDirection[3] = 1;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = TorchItem;
    .permanentEmitter[0] = weapon_smoke;
    .permanentEmitter[1] = SparksOfTorchEmitter;
    .permanentEmitterNode[0] = "smoke_node";
    .permanentEmitterNode[1] = "sparks_node";
    .fireEmitter = TestFireEmitter;
    .fireEmitterNode = "fire_node";
    .animatedBillboard = TestAnimatedBillboard;
    .animatedBillboardNode = "fire_node";
    .permanentSound = TorchFireSound;
    .lightType = ConstantLight;
    .lightColor = "1.0 1.0 0.9";
    .lightRadius = 20;
    .lightImageNode = "fire_node";
    .lightPrototype = "Torch_light";
};
datablock WeaponData(DecoratedJoustingLance : BaseMeleeWeapon)
{
    .id = 338;
    .Object_typeID = 1141;
    .shapeFile = "art/models/3d-2d/weapons/lances/jousting_lance_export_02.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = AttackPike;
    .weaponType = WeaponLance;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 2.35;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 0.5;
    .hitDirection[0] = "0 1";
    .hitDirection[1] = 1;
    .hitDirection[2] = 1;
    .hitDirection[3] = 1;
    .WoundMultiplier = 1;
    .FractureMultiplier = 0;
    .StunMultiplier = 0.3;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = DecoratedJoustingLanceItem;
    .BasePrefireAnimTime = 1;
    .BaseFireAnimTime = 3;
    .BaseRecoilAnimTime = 0.8;
    .stateCheckTransition[1] = 1;
    .stateTransitionOnAltTriggerDown[0] = "";
    .stateTransitionOnAltTriggerDown[1] = "FireCancel";
    .stateTransitionOnAltTriggerDown[2] = "FireCancel";
    .stateTransitionOnAltTriggerDown[16] = "";
};
datablock WeaponData(HandOfBoris : BaseMeleeWeapon)
{
    .id = 583;
    .Object_typeID = 1120;
    .shapeFile = "art/models/3d-2d/weapons/unarmed/fist.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = AttackUnarmed;
    .weaponType = WeaponUnarmed;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 0.7;
    .hitDirection[0] = 0;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0.1;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = HandOfBorisItem;
};
datablock WeaponData(HandOfIlyas : BaseMeleeWeapon)
{
    .id = 584;
    .Object_typeID = 1122;
    .shapeFile = "art/models/3d-2d/weapons/unarmed/fist.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = AttackUnarmed;
    .weaponType = WeaponUnarmed;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 0.7;
    .hitDirection[0] = 0;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0.1;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = HandOfIlyasItem;
};
datablock WeaponData(SiegeTorch : BaseMeleeWeapon)
{
    .id = 611;
    .Object_typeID = 1414;
    .shapeFile = "art/models/3d-2d/tools/siege_torch.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack2HWeapon;
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = siege;
    .hitGroupDmgLevel[0] = 2.4;
    .hitGroupType[1] = siege;
    .hitGroupDmgLevel[1] = 1.6;
    .hitDirection[0] = 0;
    .hitDirection[1] = 1;
    .hitDirection[2] = 1;
    .hitDirection[3] = 1;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = SiegeTorchItem;
    .permanentEmitter[0] = weapon_smoke;
    .permanentEmitter[1] = SparksOfTorchEmitter;
    .permanentEmitterNode[0] = "smoke_node";
    .permanentEmitterNode[1] = "sparks_node";
    .fireEmitter = TestFireEmitter;
    .fireEmitterNode = "fire_node";
    .animatedBillboard = TestAnimatedBillboard;
    .animatedBillboardNode = "fire_node";
    .permanentSound = TorchFireSound;
    .lightType = ConstantLight;
    .lightColor = "1.0 1.0 0.9";
    .lightRadius = 20;
    .lightImageNode = "fire_node";
    .lightPrototype = "Torch_light";
};
datablock WeaponData(BelieverShovel : BaseMeleeWeapon)
{
    .id = 650;
    .Object_typeID = 1463;
    .shapeFile = "art/models/3d-2d/tools/shovel.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack2HWeapon;
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 0;
    .hitGroupType[1] = Slashing;
    .hitGroupDmgLevel[1] = 0;
    .hitDirection[0] = 0;
    .hitDirection[1] = 1;
    .hitDirection[2] = 1;
    .hitDirection[3] = 1;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = BelieverShovelItem;
};
datablock WeaponData(BelieverHammer : BaseMeleeWeapon)
{
    .id = 651;
    .Object_typeID = 1464;
    .shapeFile = "art/models/3d-2d/tools/blacksmithhammer_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 0;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 0;
    .hitDirection[0] = 1;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = BelieverHammerItem;
};
datablock WeaponData(BelieverHatchet : BaseMeleeWeapon)
{
    .id = 652;
    .Object_typeID = 1465;
    .shapeFile = "art/models/3d-2d/tools/hatchet_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Slashing;
    .hitGroupDmgLevel[0] = 0;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 0;
    .hitDirection[0] = 1;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = BelieverHatchetItem;
};
datablock WeaponData(BelieverPickaxe : BaseMeleeWeapon)
{
    .id = 653;
    .Object_typeID = 1466;
    .shapeFile = "art/models/3d-2d/tools/pickaxe_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack2HSword;
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 0;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 0;
    .hitDirection[0] = 1;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = BelieverPickaxeItem;
};
datablock WeaponData(BelieverSaw : BaseMeleeWeapon)
{
    .id = 654;
    .Object_typeID = 1467;
    .shapeFile = "art/models/3d-2d/tools/saw_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 0;
    .hitDirection[0] = 0;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = BelieverSawItem;
};
datablock WeaponData(BelieverKnife : BaseMeleeWeapon)
{
    .id = 655;
    .Object_typeID = 1468;
    .shapeFile = "art/models/3d-2d/tools/simpleknife_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = WeaponMisc;
    .weaponMaterial = Metal;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 0;
    .hitGroupType[1] = Slashing;
    .hitGroupDmgLevel[1] = 0;
    .hitDirection[0] = 0;
    .hitDirection[1] = 1;
    .hitDirection[2] = 1;
    .hitDirection[3] = 1;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = BelieverKnifeItem;
};
datablock WeaponData(BelieverSickle : BaseMeleeWeapon)
{
    .id = 656;
    .Object_typeID = 1469;
    .shapeFile = "art/models/3d-2d/tools/sickle_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = WeaponMisc;
    .weaponMaterial = Metal;
    .hitGroupType[0] = Piercing;
    .hitGroupDmgLevel[0] = 0;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 0;
    .hitDirection[0] = 1;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = BelieverSickleItem;
};
datablock WeaponData(BelieverCrucibleTongs : BaseMeleeWeapon)
{
    .id = 657;
    .Object_typeID = 1470;
    .shapeFile = "art/models/3d-2d/tools/cas_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 0;
    .hitDirection[0] = 0;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = BelieverCrucibleTongsItem;
};
datablock WeaponData(BelieverFishingPole : BaseMeleeWeapon)
{
    .id = 658;
    .Object_typeID = 1471;
    .shapeFile = "art/models/3d-2d/tools/fishingrod_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack2HWeapon;
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 0;
    .hitDirection[0] = 0;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = BelieverFishingPoleItem;
    .BasePrefireAnimTime = 1.2;
    .BaseFireAnimTime = 1.2;
    .BaseRecoilAnimTime = 1.2;
};
datablock WeaponData(BelieverCookingPot : BaseMeleeWeapon)
{
    .id = 659;
    .Object_typeID = 1559;
    .shapeFile = "art/models/3d-2d/tools/cookingpot_export_01.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 0;
    .hitDirection[0] = 0;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = BelieverCookingPotItem;
};
datablock ShieldData(HeavyTargeShield : BaseShield)
{
    .id = 614;
    .Object_typeID = 1522;
    .shapeFile = "art/models/3d-2d/armors/shields/shield_woodenroundreg.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = WeaponShield;
    .hitDirection[0] = 0;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = HeavyTargeShieldItem;
};
datablock ShieldData(HeavyHeaterShield : BaseShield)
{
    .id = 615;
    .Object_typeID = 1523;
    .shapeFile = "art/models/3d-2d/armors/shields/shield_heaterreg.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = WeaponShield;
    .hitDirection[0] = 0;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = HeavyHeaterShieldItem;
};
datablock ShieldData(HeavyKiteShield : BaseShield)
{
    .id = 616;
    .Object_typeID = 1524;
    .shapeFile = "art/models/3d-2d/armors/shields/shield_kitereg.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = WeaponShield;
    .hitDirection[0] = 0;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = HeavyKiteShieldItem;
};
datablock ShieldData(SmallKiteShield : BaseShield)
{
    .id = 617;
    .Object_typeID = 1535;
    .shapeFile = "art/models/3d-2d/armors/shields/shield_heatera.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = WeaponShield;
    .hitDirection[0] = 0;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = SmallKiteShieldItem;
};
datablock ShieldData(HeavyIronShield : BaseShield)
{
    .id = 618;
    .Object_typeID = 1537;
    .shapeFile = "art/models/3d-2d/armors/shields/shield_steelroundreg.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack1H;
    .weaponType = WeaponShield;
    .hitDirection[0] = 0;
    .hitDirection[1] = 0;
    .hitDirection[2] = 0;
    .hitDirection[3] = 0;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0;
    .StunMultiplier = 0;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = HeavyIronShieldItem;
};
datablock WeaponData(BalancedStaff : BaseMeleeWeapon)
{
    .id = 619;
    .Object_typeID = 1408;
    .shapeFile = "art/models/3d-2d/weapons/polearms/staff.dts";
    .mountPoint = 0;
    .offset = "0 0 0";
    .eyeOffset = "0 0 0";
    .attackType = Attack2HWeapon;
    .weaponType = WeaponMisc;
    .weaponMaterial = Wooden;
    .hitGroupType[0] = Blunt;
    .hitGroupDmgLevel[0] = 1.4;
    .hitGroupType[1] = Blunt;
    .hitGroupDmgLevel[1] = 1.4;
    .hitDirection[0] = 0;
    .hitDirection[1] = 1;
    .hitDirection[2] = 1;
    .hitDirection[3] = 1;
    .WoundMultiplier = 0;
    .FractureMultiplier = 0.5;
    .StunMultiplier = 0.05;
    .correctMuzzleVector = 0;
    .className = "WeaponImage";
    .item = BalancedStaffItem;
    .BasePrefireAnimTime = 1.1;
    .BaseFireAnimTime = 1.05;
    .BaseRecoilAnimTime = 1;
};

